language: php

php:
  - 7.3
  - 8.0
  - 8.1

services:
  - redis

before_script:
  - composer self-update
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit tests

after_script:
  - php vendor/bin/coveralls -v
