version: '3'
services:
  php:
    build: ./docker/php
    working_dir: /app
    volumes:
      - "./:/app:cached"
    environment:
      - XDEBUG_MODE=coverage

  redis:
    image: "redis:alpine"
    depends_on:
      - php
