name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5.20
          configuration: phpunit.xml.dist
          php_version: 8.1
          php_extensions: posix
