name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d

      - name: Install dependencies
        run: docker-compose exec -T php composer install

      - name: Run PHPUnit Tests
        run: docker-compose exec -T php vendor/bin/phpunit

      - name: Upload coverage results to Coveralls
        run: docker-compose exec -e COVERALLS_REPO_TOKEN="${{ secrets.COVERALLS_REPO_TOKEN }}" -T php vendor/bin/php-coveralls -v
