name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d

      - name: Install dependencies
        run: docker-compose run php composer install

      - name: Run PHPUnit Tests
        run: docker-compose run php vendor/bin/phpunit
